### ISSUE TITLE
Criar edição de series

### ISSUE THREAD

**Issue by ronymmoura** [shipper-app/fitzdb#2]
Na tela principal, ao lado do botão de exclusão, criar um botão que possibilite a edição da serie.

**Comment by Amandavss** [comment]
Consegui

**Comment by Amandavss** [comment]
Uma pergunta, quando a gente tiver cadastrando a série, tem como quando ela já estiver cadastrada e a gente estiver digitando o nome já aparecer o nome embaixo completo como um aviso que ela já existe?
Pq ele só nos avisa isso depois de preencher tudo e dá o OK

**Comment by ronymmoura** [comment]
Abre uma issue nova pedindo pra implementar isso pra registrar as tarefas e pans

**Comment by ronymmoura** [comment]
Commit [7879a69](https://github.com/shipper-app/fitzdb/releases/tag/v0.0.11)
