### ISSUE TITLE
Aviso série já cadastrada

### ISSUE THREAD

**Issue by Amandavss** [shipper-app/fitzdb#3]
Quando a gente tiver cadastrando a série, tem como quando ela já estiver cadastrada e a gente estiver digitando o nome dela, já aparecer o nome embaixo completo como um aviso que ela já existe?
Pq ele só nos avisa isso depois de preencher tudo e dá o OK

**Comment by ronymmoura** [comment]
Commit [7879a69](https://github.com/shipper-app/fitzdb/releases/tag/v0.0.11)
